
## Goal - this will say hello and show the name of the repository.

## Start with the name of the repository.
name: "Hello workflows"

## When the workflow runs i.e it tells when will the workflow runs which it automatically 
on:    
  push:
    branches: [main]

  #push: 
    #workflow_dispatch:   ## This will use when you want to run the code by yourself using button.

jobs:     ## what is the workflow do
  
  greet:   ## name of the job
    runs-on: ubuntu-latest   ## Where the job runs i.e. on which OS

    ## The steps or sequence of the job does.
    steps:
      - name: Say hello
        run: echo "Hello Dosto"

  repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Show repository name
        run: echo "The repository name is ${{ github.event.repository.name }}"

  
  
